# Generated by Django 3.0.10 on 2020-09-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_pricing_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pricing_tiers',
            field=models.ManyToManyField(blank=True, to='content.Pricing'),
        ),
    ]
