# Generated by Django 3.0.10 on 2020-09-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_course_pricing_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='currency',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=17, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='slug',
            field=models.SlugField(default='17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='stripe_price_id',
            field=models.CharField(default=17, max_length=50),
            preserve_default=False,
        ),
    ]
